# Warsztaty: Deep Learning
## Zadanie 1
###### Marta Kałużna

In [1]:
# %tensorflow_version 2.x - switch only for Google Colab notebook
%tensorflow_version 2.x

import tensorflow as tf
print(tf.__version__)

TensorFlow 2.x selected.
2.1.0


In [2]:
from tensorflow import keras
from keras import datasets
import numpy as np

Using TensorFlow backend.


Fashion MNIST dataset

In [ ]:
fashion_mnist = keras.datasets.fashion_mnist

In [ ]:
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data() # training set, test set

In [5]:
X_train.shape

(60000, 28, 28)

In [6]:
len(y_train)

60000

In [7]:
y_train

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [8]:
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [9]:
X_train = X_train.reshape((-1, 28*28))
X_train.shape

(60000, 784)

In [ ]:
X_train = X_train/255.0
X_test = X_test/255

In [11]:
X_train = tf.convert_to_tensor(X_train, dtype = float)
print(X_train)

tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(60000, 784), dtype=float32)


In [12]:
y_train = tf.convert_to_tensor(y_train)
print(y_train)

tf.Tensor([9 0 0 ... 3 0 5], shape=(60000,), dtype=uint8)


In [13]:
print(X_train.shape, y_train.shape)

(60000, 784) (60000,)


In [ ]:
tf.random.set_seed(12345)

W1 = tf.Variable(tf.random.normal((784, 1000)))
b1 = tf.Variable(tf.random.normal((1000,)))

W2 = tf.Variable(tf.random.normal((1000, 100)))
b2 = tf.Variable(tf.random.normal((100,)))

W3 = tf.Variable(tf.random.normal((100, 50)))
b3 = tf.Variable(tf.random.normal((50,)))

W4 = tf.Variable(tf.random.normal((50, 10)))
b4 = tf.Variable(tf.random.normal((10,)))

Forward propagation

In [ ]:
def forward_propagation(X, W1, b1, W2, b2, W3, b3, W4, b4):
    A0 = X

    Z1 = tf.matmul(A0, W1) + b1
    A1 = tf.tanh(Z1)

    Z2 = tf.matmul(A1, W2) + b2
    A2 = tf.tanh(Z2)

    Z3 = tf.matmul(A2, W3) + b3
    A3 = tf.tanh(Z3)

    Z4 = tf.matmul(A3, W4) + b4
    A4 = tf.nn.softmax(Z4)

    y_hat = A4
    return Z4, y_hat # logits, softmax

In [16]:
forward_propagation(X_train, W1, b1, W2, b2, W3, b3, W4, b4)

(<tf.Tensor: shape=(60000, 10), dtype=float32, numpy=
 array([[ 14.4709015 ,   7.601225  ,  -5.8585067 , ...,  -3.3783667 ,
           5.461572  ,   6.441334  ],
        [ -8.397575  ,   2.4900904 ,   5.5836616 , ...,  -1.568797  ,
          -7.911801  ,  -9.143809  ],
        [  1.2973833 ,  -3.8241618 ,  -5.3570547 , ...,  -1.6864058 ,
          -5.1438284 , -11.589508  ],
        ...,
        [  0.48657715,  -0.12495065, -15.358458  , ...,  -0.85546327,
          -1.1798108 ,  -7.570033  ],
        [ -6.1302495 ,  -5.596167  ,   2.4881506 , ...,  -9.005307  ,
          -5.0038934 ,  -1.6769586 ],
        [ -9.3058815 ,   1.8453324 ,  -5.712049  , ...,  -8.247258  ,
          -4.4375167 ,   8.906017  ]], dtype=float32)>,
 <tf.Tensor: shape=(60000, 10), dtype=float32, numpy=
 array([[9.38825727e-01, 9.75264411e-04, 1.39198642e-09, ...,
         1.66244156e-08, 1.14784489e-04, 3.05765192e-04],
        [2.24642775e-08, 1.20211381e-03, 2.65134629e-02, ...,
         2.07583635e-05, 3.6514

Loss function

In [ ]:
def loss(X, Y, W1, b1, W2, b2, W3, b3, W4, b4):

    Z4, y_hat = forward_propagation(X, W1, b1, W2, b2, W3, b3, W4, b4)

    return tf.reduce_mean(
        tf.nn.softmax_cross_entropy_with_logits(labels = tf.one_hot(Y, depth=10), logits = Z4)
    )

In [18]:
loss(X_train, y_train, W1, b1, W2, b2, W3, b3, W4, b4)

<tf.Tensor: shape=(), dtype=float32, numpy=10.646508>

GD

In [ ]:
with tf.GradientTape() as gradient_tape:
    L = loss(X_train, y_train, W1, b1, W2, b2, W3, b3, W4, b4)
dW1, db1, dW2, db2, dW3, db3, dW4, db4 = gradient_tape.gradient(L, [W1, b1, W2, b2, W3, b3, W4, b4])

In [20]:
alpha = tf.constant(0.1, dtype=float)

W1.assign_sub(alpha * dW1)
W2.assign_sub(alpha * dW2)
W3.assign_sub(alpha * dW3)
W4.assign_sub(alpha * dW4)

b1.assign_sub(alpha * db1)
b2.assign_sub(alpha * db2)
b3.assign_sub(alpha * db3)
b4.assign_sub(alpha * db4)

loss(X_train, y_train, W1, b1, W2, b2, W3, b3, W4, b4)

<tf.Tensor: shape=(), dtype=float32, numpy=9.882531>

In [21]:
epochs = 20

for i in range(epochs):
    with tf.GradientTape() as gradient_tape:
        L = loss(X_train, y_train, W1, b1, W2, b2, W3, b3, W4, b4)
    dW1, db1, dW2, db2, dW3, db3, dW4, db4 = gradient_tape.gradient(L, [W1, b1, W2, b2, W3, b3, W4, b4])
    W1.assign_sub(alpha * dW1)
    W2.assign_sub(alpha * dW2)
    W3.assign_sub(alpha * dW3)
    W4.assign_sub(alpha * dW4)

    b1.assign_sub(alpha * db1)
    b2.assign_sub(alpha * db2)
    b3.assign_sub(alpha * db3)
    b4.assign_sub(alpha * db4)


    print("Step {:3d}/{:3d} : loss = {:.5f}".format(i+1, epochs, L))

Step   1/ 20 : loss = 9.88253
Step   2/ 20 : loss = 9.25274
Step   3/ 20 : loss = 8.73621
Step   4/ 20 : loss = 8.28123
Step   5/ 20 : loss = 7.89297
Step   6/ 20 : loss = 7.56822
Step   7/ 20 : loss = 7.28979
Step   8/ 20 : loss = 7.04243
Step   9/ 20 : loss = 6.81435
Step  10/ 20 : loss = 6.60302
Step  11/ 20 : loss = 6.40360
Step  12/ 20 : loss = 6.21553
Step  13/ 20 : loss = 6.04096
Step  14/ 20 : loss = 5.87850
Step  15/ 20 : loss = 5.72794
Step  16/ 20 : loss = 5.58878
Step  17/ 20 : loss = 5.46037
Step  18/ 20 : loss = 5.33877
Step  19/ 20 : loss = 5.22537
Step  20/ 20 : loss = 5.11652


Prediction

In [22]:
X_test.shape

(10000, 28, 28)

In [ ]:
X_test = X_test.reshape((-1, 28*28))
X_test = tf.convert_to_tensor(X_test, dtype = float)
y_test = tf.convert_to_tensor(y_test)

In [ ]:
Z4, y_hat = forward_propagation(X_test, W1, b1, W2, b2, W3, b3, W4, b4)

In [25]:
y_hat

<tf.Tensor: shape=(10000, 10), dtype=float32, numpy=
array([[3.38741302e-06, 1.40142165e-05, 3.75460018e-04, ...,
        4.38619310e-08, 1.01197736e-06, 3.23421809e-05],
       [1.56303827e-06, 3.15188970e-07, 6.92416279e-07, ...,
        4.81260986e-06, 9.70943570e-02, 3.13441946e-11],
       [8.36174763e-07, 1.65359378e-02, 2.45935627e-08, ...,
        2.49400341e-06, 1.73773333e-05, 6.54969824e-07],
       ...,
       [4.16963436e-02, 2.80411854e-08, 1.61888875e-05, ...,
        1.34483507e-05, 3.35094121e-08, 1.10767678e-06],
       [2.00931751e-07, 9.99572814e-01, 1.75186016e-12, ...,
        3.77276677e-07, 6.14945009e-07, 3.28224080e-11],
       [5.38976394e-07, 3.75861440e-08, 1.22556392e-08, ...,
        6.89329505e-02, 9.60805977e-04, 2.66941206e-05]], dtype=float32)>

In [ ]:
prediction = tf.math.argmax(y_hat, 1)

In [27]:
prediction, y_test

(<tf.Tensor: shape=(10000,), dtype=int64, numpy=array([6, 4, 3, ..., 6, 1, 5])>,
 <tf.Tensor: shape=(10000,), dtype=uint8, numpy=array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)>)

Accuracy

In [28]:
results = tf.equal(prediction, tf.cast(y_test, dtype='int64'))
results

<tf.Tensor: shape=(10000,), dtype=bool, numpy=array([False, False, False, ..., False,  True,  True])>

In [29]:
accuracy = tf.reduce_mean(tf.cast(results, dtype = 'float32'))
print(accuracy.numpy())

0.2682
